### ISSUE TITLE
Not on npm

### ISSUE THREAD

**Issue by fregante** [es-tooling/module-replacements-codemods#6]
Don't forget to publish it before others do

```
$ npx module-replacements-codemods
npm error code E404
npm error 404 Not Found - GET https://registry.npmjs.org/module-replacements-codemods - Not found
npm error 404
npm error 404  'module-replacements-codemods@*' is not in this registry.
npm error 404
npm error 404 Note that you can also install from a
npm error 404 tarball, folder, http url, or git url.
```

**Comment by thepassle** [comment]
Thanks for making this issue :) The name is still up in the air a bit (open for suggestions!), and the CLI as-is is _very_ barebones. For now the focus of this repository is just to get the codemods created; once we have a substantial amount of replacement codemods, we can think of a good way of implementing the CLI, figure out a good name, publish it, and market it.

**Comment by danieldelcore** [comment]
`@e18e/codemods` 🤔

**Comment by thepassle** [comment]
The codemods have been published on npm now https://www.npmjs.com/package/module-replacements-codemods
