### ISSUE TITLE
approaching `define-properties`

### ISSUE THREAD

**Issue by andrico1234** [es-tooling/module-replacements-codemods#66]
[In the `module-replacement` repo](https://github.com/es-tooling/module-replacements/blob/main/manifests/native.json#L989), `define-properties` is listed as a replaceable by `Object.defineProperties`. 

After doing some investigating, there is considerable discrepancy between the two functions.

## `define-properties`

```javascript
const define = require('define-properties');
const assert = require('assert');

const res1 = define({ a: 1, b: 2 }, {
  a: 10,
  b: 20,
  c: 30
});

assert(res1.a === 1);
assert(res1.b === 2);
assert(res1.c === 30);

assert.deepEqual(Object.keys(res1), ['a', 'b']);
assert.deepEqual(Object.getOwnPropertyDescriptor(res1, 'c'), {
  configurable: true,
  enumerable: false,
  value: 30,
  writable: false
});

```

## Object.defineProperties()

```javascript
const obj = { a: 1, b: 2 };

const res1 = Object.defineProperties(obj, {
  a: {
    value: 10
  },
  b: { value: 20 },
  c: { value: 30, configurable: true }
});

assert(res1.a === 10);
assert(res1.b === 20);
assert(res1.c === 30);

assert.deepEqual(Object.keys(res1), ['a', 'b']);
assert.deepEqual(Object.getOwnPropertyDescriptor(res1, 'c'), {
  configurable: true,
  enumerable: false,
  value: 30,
  writable: false
});
```

There are a few things worth noting:

1. Both have different function signatures
2. If only values are provided to the second argument, the property descriptors in the results are not the same
3. By default, `define-properties` doesn't overwrite existing properties, whereas `Object.defineProperties` does.

In addition `define-properties` also allows a third argument, overwrite predicate functions, which does not exist at all for `Object.defineProperties`

This means that if we wanted to provide a codemod, we'd also need to include additional functionality. e.g., to identify existing properties and prevent overwrites, among other functionality.

## What's next

So the questions are:

1. What's the precedence for this kind of situation? Do we only want to do simple transformations for these "replaceable" modules. Or we do want to migrate divergent behaviour?
2. What do we want to do specifically with `define-properties`? e.g., migrate to `Object.defineProperties` while also preventing overwrites by default? Do we want to support the overwrites predicate functions?

## Bonus

[Justin mentioned](https://discord.com/channels/1227627367204257852/1266413897989099632/1266433847768256595) that we could take an iterative approach and only migrate in certain scenarios. 

Full initial discussion is also in the thread

## Resources

- [Initial discussion](https://discord.com/channels/1227627367204257852/1227627367204257855/1266413897989099632)
- [Object.defineProperties](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperties)
- [define-properties](https://github.com/ljharb/define-properties)

**Comment by thepassle** [comment]
I think it would make sense to take a look at the usecases of this package, to get a feel for what the most common usage of it is, and then codemod that. Perhaps we can then also implement some kind of additional logging with a link to a docs page that goes into some nuances of things/usecases that the codemod didnt handle. So then if somebody runs the codemod, and this particular codemod is applied, if they run into issues, they are aware that there are some edgecases and get a link to the docs.

**Comment by ljharb** [comment]
Indeed, `define-properties` has nothing to do with `Object.defineProperties`, despite my many attempts to clarify that.

The intended use cases are to conditionally overwrite methods/properties based on whether the current engine needs the property overwritten (iow, whether it's missing or broken, for polyfills).

Use cases where the predicate is not provided can indeed be codemodded to use Object.defineProperties.

Use cases where the predicate is provided and the object is literally present in source code _could_ be codemodded into multiple `if` statements, each using `Object.defineProperty`.

**Comment by justinfagnani** [comment]
I see some usage out there of just the `supportsDescriptors` property. That should just be replaced with `true`, and ideally expressions that use it are simplified and unreachable branches are eliminated. I don't know if that's a bit much for a codemod.

Are there utilities out there to help with targeted dead-code elimination? I'd want that to only simplify code that depends on `supportsDescriptors`, not all code.

**Comment by ljharb** [comment]
Additionally, any place that only depends on `define-properties` for the `supportsDescriptors` property should be updated to use `require('has-property-descriptors')()` anyways (which should be replaced with `true` for any engine support range in which that value is known to always be `true`).

**Comment by justinfagnani** [comment]
I don't think that's necessary. People really don't need to support Chrome 4 and Node 0.9. Let's not encourage another dependency that's useless in 100% of practical cases.

**Comment by ljharb** [comment]
You can choose what to encourage yourself and there's no need to argue that here; I'm just providing information to ensure correctness (note my parenthetical above which addresses your implied concern).

**Comment by andrico1234** [comment]
Thanks fellas for taking the time to contribute to the issue.

Here are the three main use cases for `define-properties`:

(my apologies if the following restates the obvious for the folks involved in this chat, I've re-spelled it out to get my ducks in a row and ensure that the next steps are clear)

## 1. Defining Properties

`define(object, map)`

This defines properties from `map` over to `object` without overwriting properties of the same name. 

This could be codemodded, but would require a little bit additional logic. I'll open up a PR for this

## 2. Conditionally Defining Properties

`define(object, map, predicates)`

This defines properties from `map` over to `object` but only overwrites the existing property if the corresponding predicate function returns `true`.

## 3. Checking Descriptors Support

`const supportsDescriptors = require('define-properties').supportDescriptors`

A boolean flag that returns true if the environment supports `defineProperty`. We can codemod to `true` since this `supportDescriptors` would return `false` for ES3 and IE8 environments. 

## Next Steps

1. Codemod for supportsDescriptors and swap the boolean out for `true`.
2. Codemod for when `define` is used without as third argument
3. Codemod for when `define` is used with a third argument, but only add a comment that explains the problem, or links to a resource explaining the problem in greater depth (maybe even this GitHub issue)

**Comment by ljharb** [comment]
@andrico1234 thanks; the readme is wrong and wasn't being tested. I've fixed the readme in https://github.com/ljharb/define-properties/commit/3c9a6da54291c6964d40e3691ab8301611994a15 and it's now tested to ensure it remains correct.
